"""empty message

Revision ID: 1e0d875263ad
Revises: 52efe5ee2f21
Create Date: 2026-03-02 09:36:23.826314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0d875263ad'
down_revision = '52efe5ee2f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['vehicle.car_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('coment',
    sa.Column('coment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('coment_text', sa.String(length=450), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['post_spot.spot_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('coment_id')
    )
    with op.batch_alter_table('media_vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_vehicle', sa.String(length=255), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('url_vehicle')

    op.drop_table('coment')
    op.drop_table('booking')
    # ### end Alembic commands ###
