"""empty message

Revision ID: 52efe5ee2f21
Revises: 
Create Date: 2026-02-28 11:11:39.400303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52efe5ee2f21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('vehicle',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type_vehicle', sa.String(length=120), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_table('media_vehicle',
    sa.Column('media_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['vehicle.car_id'], ),
    sa.PrimaryKeyConstraint('media_vehicle_id')
    )
    op.create_table('post_spot',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_sleepable', sa.Boolean(), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=True),
    sa.Column('has_waste_dump', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('spot_id')
    )
    op.create_table('media_spot',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_spot.spot_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_spot')
    op.drop_table('post_spot')
    op.drop_table('media_vehicle')
    op.drop_table('vehicle')
    op.drop_table('user')
    # ### end Alembic commands ###
