"""empty message

Revision ID: 57a2bd19ef26
Revises: 9113b880d53f
Create Date: 2026-03-09 10:12:13.792100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a2bd19ef26'
down_revision = '9113b880d53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_formatted', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('has_electricity', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')

    with op.batch_alter_table('post_spot', schema=None) as batch_op:
        batch_op.drop_column('has_electricity')
        batch_op.drop_column('phone_formatted')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
