"""empty message

Revision ID: 9113b880d53f
Revises: 1e0d875263ad
Create Date: 2026-03-04 10:55:39.225005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9113b880d53f'
down_revision = '1e0d875263ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorire_spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Spot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Spot_id'], ['post_spot.spot_id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_van',
    sa.Column('review_van_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bookking_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('coment_review', sa.String(length=450), nullable=True),
    sa.Column('rating_review', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookking_id'], ['booking.booking_id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['vehicle.car_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('review_van_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_van')
    op.drop_table('favorire_spot')
    # ### end Alembic commands ###
